sudo: required

services:
  - docker

before_install:

- apt purge npm
- curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
- sudo apt-get install -y nodejs
- npm i -g truffle
- docker-compose up &>/dev/null &

script:
- npm i
- truffle test